### ISSUE TITLE
Background File-upload does not work

### ISSUE THREAD

**Issue by lennybacon** [wdr-data/code4maus#8]
### Expected Behavior

The file upload for a background should work

### Actual Behavior

Clicking the upload icon does not do anything

### Steps to Reproduce
- Open the [app](https://programmieren.wdrmaus.de/lernspiel/00)
- Click on the `Weiter` button in the tutorial (lower right frame).
- Click on the `Hintergrund` button in the stage selector (lower left frame).
  - The second tab above the main frame flips to `Hintergründe`
- Click on the `Hintergrund` tab
  - The `Hintergründe` menu opens in the main frame
- Click on the `Upload` icon in the tools panel (lower left)
  - Nothing happens
- Hit `F12` to open the dev-tools to view the error

```
TypeError: this.fileInput is undefined, can't access property "click".
```

I set a breakpoint...

```javascript
value: function () {
  this.fileInput.click()
}
```

... and `fileInput` is undefined:

![image](https://user-images.githubusercontent.com/272164/46151665-91518f80-c26f-11e8-83be-2c892c4158d2.png)

### Operating System and Browser
- Windows, Mozialla Dev 63.0b9

**Comment by mraerino** [comment]
Thank you for this and sorry we did not reply earlier!

This has been fixed by https://github.com/wdr-data/code4maus/commit/edeaed1eb6fdbb7b56841934a35606f67a7509b9 and will soon be released into production.

**Comment by lennybacon** [comment]
@mraerino "develop and production are identical."  Since "Release to production #10" by @christinegotth on Nov 26, 2018. So I close the issue. Thanks much!
